import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import LateralMenu from './components/templates/LateralMenu'

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <div className={` flex h-screen w-screen`}>
          <LateralMenu />
          <div
            className={`flex flex-col w-full p-7 bg-gray-300 dark:bg-gray-800`}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
